title: あやめHex
email: daiusa3@icloud.com
description: >-
  競技プログラミングやCTFなどのライブラリ
author: anko9801
domain: anko9801.github.io
baseurl: "/library"
url: "https://anko9801.github.io"
twitter_username: Anko_9801
github_username: anko9801
theme: minima

markdown: kramdown
lang: ja
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-linkpreview
timezone: Asia/Tokyo

collections:
  snippets:
    output: true
